project:
  type: website
  output-dir: docs

website:
  title: 'Krishnakant A'
  page-navigation: False
  favicon: escher.tiff
  navbar: 
  
    search: true
    background: primary
    collapse-below: lg
    left:
      - href: index.qmd
      - href: docu/anotherpage.qmd
        text: "Home"
      - text: "Sea of Everything"
        file: docu/SEA/index.qmd
      - text: "Implementations"
        href: docu/Book_Implementations/index.qmd
      - text: "Resources"
        href: docu/Resources/index.qmd
      - text: "Help"
        menu: 
          - text: "report a bug"
  sidebar:
    - id: Sea_of_everything
      title: "Sea of Everything"
      style: "docked"
      background: dark
      collapse-level: 1
      align: left
      contents:
        - text: "Introduction"
          href: docu/SEA/index.qmd
        - section: "Computer Science"
          collapse: true
          contents:
            - text: "Programming languages"
              href: docu/SEA/python.qmd
            - text: "Complexity Theory"
            - text: "DSA"
              href : docu/SEA/DSA.qmd
        - section: "Quantitative Finance"
          href: docu/SEA/Q_F/index.qmd
          contents:
            - text: "Stochastic Calculus"
              href: docu/SEA/StochC.qmd
            - text: "Time series analysis"
              href: docu/SEA/time_series.qmd
            - text: "Statistics"
              href: "docu/SEA/Q_F/statistics.qmd"
            - text: "Interest rate models"
              href: docu/SEA/IRM.qmd
              
        - section: "Crypto/Blockchain"
          href: docu/Crypto/index.qmd
          contents:
            - text: "EVM and Defi stuff"
              href: docu/Crypto/evmdefi.qmd
            - text: "Cryptography" 
        
        - section: "Mathematics"
          contents:
            - text: "P-Adic Calculus"
            - text: "Number Theory"
            - text: "Galois Theory"
            - text: "Analysis"
                
        
        
       # - section: "Traditional Finance"
        #  contents: 
         #   - text: "Technical Analysis"
           # - text: "Fudamental Analysis"
          #  - text: "Financial Products"
            
        - section: "Machine Learning"
          contents: 
            - text: "Data Analysis"
              href: docu/SEA/data_analysis.qmd
            - text: "Machine Learning Theory and Practice"
              href: docu/SEA/Machine learning/handsonml.qmd
            - text: "Machine Learning for finance"
              href: docu/SEA/Machine learning/Machine Learning for finance.qmd
              
        - text: "Interesting Implementations"
          href: docu/SEA/Interesting_implementation.qmd
    - id: Resources
      title: "Resources"
      style: "docked"
      background: dark
      collapse-level: 1
      align: left
      contents:
        - text: "List of Resources"
          href: docu/Resources/index.qmd
        - text: "Cheat Sheets"
          href: docu/Resources/coding.qmd
    
        - text: "Research Papers"
          href: docu/Resources/Research_papers.qmd
    
    - id: Implementations
      title: "Implementations"
      style: "docked"
      background: dark
      collapse-level: 1
      align: left
      contents:
        - text: "Implementations"
          href: docu/Book_Implementations/index.qmd
        #- text: "First Course stochastic calculus" 
          #href: docu/Book_Implementations/FCSC.qmd
          
    - id: project      
   ###
    # - id: Book_Implementation
    #   title: "Book Implementation"
    #   style: "docked"
    #   background: dark
    #   collapse-level: 1
    #   align: left
    #   contents:
    #      - text: "Introduction"
    #        href: docu/Book_Implementations/index.qmd
    #      - section: "Hands On Machine Learning "
    #        contents:
    #          - text: "Programming"
    #          - text: Python
    #           
    #      - section: "Quantitative Finance"
    #        contents:
    #          - text: Stochastic Calculus
    #            
    #           
    #      - section: "Crypto/Blockchain"
    #        contents:
    #          - text: EVM 
    #              
    #     
    #      - section: "Mathematics"
    #        contents:
    #          - text: Abstract
    #             
    #     
    #      - section: "Books "
    #        contents:
    #          - text: "Overview"                 
        
   ###
  

format:
  html:
    theme: sketchy
    toc: true
    toc-location: right
    toc-depth: 4
jupyter: python3
    

