project:
  type: website
  output-dir: docs
website:
  title: "Krishnakant A"
  image : Escher Small.png
  favicon: "Escher Small.png"
  page-navigation: true
  navbar:
     
    search: true
    background: primary
    collapse-below: lg
    left:
      - href: index.qmd
        text: "Home"
      - text: About
        href: docu/about.qmd
      - text: Project
        href: docu/project.qmd
      - text: Sea of Everything
        file: docu/SEA/Sea_of_everything.qmd
      - text: Paper implementations
        href: docu/paper implementation.qmd
      - text: "Help"
        menu: 
          - text: "report a bug"
      
  sidebar:
    - id: Sea of Everything
      title: "Sea of Everything"
      style: "docked"
      background: light
      collapse-level: 1
      align: left
      contents:
        - docu/SEA/Programming.qmd
        
    
      
        
  
          
 
        
format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    self-contained-math: true

editor: visual

