project:
  type: website
  output-dir: docs
website:
  title: "Krishnakant A"
  image : Escher Small.png
  favicon: "Escher Small.png"
  page-navigation: true
  navbar:
     
    search: true
    background: primary
    collapse-below: lg
    left:
      - href: index.qmd
        text: "Home"
      - text: About
        href: docu/about.qmd
      - text: "Project"
        href: docu/project.qmd
      - text: "Sea of Everything"
        file: docu/SEA/index.qmd
      - text: "Paper implementations"
        href: docu/paper implementation.qmd
      - text: "Help"
        menu: 
          - text: "report a bug"
      
  sidebar:
    - id: Sea_of_everything
      title: "Sea of Everything"
      style: "docked"
      background: light
      collapse-level: 1
      align: left
      contents:
        - text: "Introduction"
          href: docu/SEA/index.qmd
        - section: "Programming"
          contents:
            - text: Programming
              href: docu/SEA/programming.qmd
        
    - id: project
      
      
        
  
          
 
        
format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    self-contained-math: true

editor: visual

