project:
  type: website
  output-dir: docs
  
website:
  title: "Krishnakant A"
  page-navigation: true
  
  navbar:
     
    search: true
    background: primary
    collapse-below: lg
    left:
      - href: docu/anotherpage.qmd
        text: "Home"
      - text: About
        href: docu/about.qmd
      - text: "Book Implementation"
        href: docu/project.qmd
      - text: "Sea of Everything"
        file: docu/SEA/index.qmd
      - text: "Paper implementations"
        href: docu/paper implementation.qmd
      - text: "Help"
        menu: 
          - text: "report a bug"
      
  sidebar:
    - id: Sea_of_everything
      title: "Sea of Everything"
      style: "docked"
      background: dark
      collapse-level: 1
      align: left
      contents:
        - text: "Introduction"
          href: docu/SEA/index.qmd
        - section: "Programming"
          contents:
            - text: Programming
              href: docu/SEA/math.qmd
            - text: Python
              
        - section: "Quantitative Finance"
          contents:
            - text: Stochastic Calculus
              
              
        - section: "Crypto/Blockchain"
          contents:
            - text: EVM 
                
        
        - section: "Mathematics"
          contents:
            - text: Abstract
                
        
        - section: "Books "
          contents:
            - text: "Overview"
                 
        
    - id: project

format:
  html:
    theme: sketchy
    toc: true
    self-contained-math: true
   
    

