---
title : "Sea of Everything" 
---

Inspired by the Rising Sea : Foundations of algebriac geomtery By Professor Ravi Vakil , which covers pretty much everything one needs to master Algebraic geometry. I have titled this section as Sea of Everything where I would be covering all my current interests related to fields of financial mathematics,programming , machine learning , crypto , etc...

My Home page would host articles that I have written to explain myself the inner - working of an idea or a concept and which are fascinating enough to be highlighted amidst all of this.

The current direction of this ***section*** mostly looks like combination of notes and insights.

I have included my hand written notes for few sections. I would be adding hand written notes and expand them as I keep on coming across various subtopics within the subject.

Initially I had the plan to type the content but given my current over demanding job, I have decided to keep a mix of both written and typed sections.

Apologies for my handwriting it's terrible I know.

P.S - It looks like my initial aim was quite ambitious given the timeframe I set for myself. I originally planned to organize the content on my website in a very structured manner, starting with preliminaries and then moving on to the main topics. However, I've realized that this approach has been quite time-consuming. Therefore, I've decided to focus on including mostly definitions and important information regarding topics in the SEA section. I plan to merge the Implementations section with SEA in the future, but for now, they will remain separate. The current outline of the website represents my vision, but as I add content, I will adjust the structure as needed.

